SELECT
  GLOBAL_INDEX,
  EVENT_IDENTIFIER,
  UTF8TOSTRING(META_DATA) AS META_DATA,
  UTF8TOSTRING(PAYLOAD) AS PAYLOAD,
  PAYLOAD_TYPE,
  TIME_STAMP,
  AGGREGATE_IDENTIFIER,
  SEQUENCE_NUMBER,
  TYPE
FROM
  DOMAIN_EVENT_ENTRY